const fallbackSnapshot = {
  generatedAt: new Date().toISOString(),
  model: {
    status: "fallback",
    scoredCount: 0,
    model: null,
    explainability: null,
    topRankings: []
  },
  note: {
    headline: "Fallback snapshot loaded; run the refresh script for current metrics.",
    body: "This fallback appears only when data/snapshot.json is unavailable. It is sample data and should not be treated as a current market read.",
    changed: [
      "No live snapshot was loaded.",
      "Run node scripts/update-data.mjs to rebuild the dashboard data.",
      "Current source, macro, and momentum metrics are unavailable in fallback mode."
    ],
    watch: [
      "Check that the local server is running from the project folder.",
      "Check that data/snapshot.json exists.",
      "Check the browser console if the dashboard continues to show fallback data."
    ]
  },
  marketDataStatus: {
    status: "fallback",
    message: "Fallback sample data is displayed because a current snapshot was not loaded.",
    staleDataReused: false
  },
  marketIntelligence: {
    professionalDrivers: [],
    earnings: { earningsMovers: [] },
    reddit: { topTickers: [] }
  },
  marketStrip: [
    { symbol: "SPY", label: "S&P 500", price: 520.12, changePct: 0.42 },
    { symbol: "QQQ", label: "Nasdaq 100", price: 442.33, changePct: 0.68 },
    { symbol: "IWM", label: "Russell 2000", price: 205.71, changePct: -0.18 },
    { symbol: "TLT", label: "20Y Treasury", price: 91.52, changePct: 0.24 },
    { symbol: "GLD", label: "Gold", price: 218.44, changePct: 0.12 },
    { symbol: "HYG", label: "High Yield", price: 78.31, changePct: 0.09 }
  ],
  sectorPerformance: [
    {
      sector: "Technology",
      symbol: "XLK",
      change1d: 0.4,
      change5d: 1.8,
      change30d: 6.1,
      ytd: 14.2,
      relative30d: 2.4,
      above50: true,
      above200: true,
      rsi14: 63,
      history: [199, 201, 203, 204, 205, 207, 208, 210, 212, 214]
    }
  ],
  recommendations: [
    {
      label: "Metric Match",
      symbol: "NVDA",
      title: "Score 86; RSI 68",
      rationale: "NVDA: above 50-day and 200-day averages; 20-day return +12.40%; volume 1.42x 20-day average."
    },
    {
      label: "Near Threshold",
      symbol: "XLK",
      title: "Score 79; ETF",
      rationale: "XLK: above 50-day and 200-day averages; 20-day return +6.10%; volume 1.18x 20-day average."
    },
    {
      label: "RSI Above Limit",
      symbol: "GOOGL",
      title: "RSI above configured ceiling",
      rationale: "GOOGL: RSI is above the configured ceiling; review the generated snapshot for current return and relative-strength values."
    }
  ],
  aiRecommendations: {
    status: "disabled",
    model: null,
    usage: null,
    headline: "AI synthesis is ready once OPENAI_API_KEY is configured.",
    macroView: "AI synthesis is disabled until OPENAI_API_KEY is configured.",
    recommendations: [],
    portfolioNotes: [
      "No AI call was made for this snapshot.",
      "Rules-based metrics are still available in the Daily Read, Desk Calls, and Momentum Book."
    ],
    openQuestions: [
      "OPENAI_API_KEY is not configured.",
      "Run the refresh after configuring an API key to populate this section."
    ],
    sourceRefs: []
  },
  deeperRead: {
    status: "unavailable",
    lookbackDays: 7,
    summary: "Deeper Read is generated by the AI layer once the dashboard snapshot is available.",
    cards: []
  },
  avoidList: {
    status: "fallback",
    summary: "Stay-away candidates are generated from the lowest-ranked model names once the daily snapshot is available.",
    sectors: [],
    companies: []
  },
  opportunities: [
    {
      symbol: "NVDA",
      name: "NVIDIA Corporation",
      type: "stock",
      sector: "Information Technology",
      score: 86,
      close: 934.12,
      rsi14: 68,
      volumeRatio: 1.42,
      return20: 12.4,
      above50: true,
      above100: true,
      above200: true,
      recentCross: true,
      relativeStrength: 8.8,
      history: [795, 802, 811, 836, 829, 852, 871, 881, 904, 934],
      tags: ["50/200 uptrend", "Volume support", "Leadership"]
    },
    {
      symbol: "XLK",
      name: "Technology Select Sector SPDR Fund",
      type: "etf",
      sector: "Sector",
      score: 79,
      close: 214.18,
      rsi14: 63,
      volumeRatio: 1.18,
      return20: 6.1,
      above50: true,
      above100: true,
      above200: true,
      recentCross: false,
      relativeStrength: 3.3,
      history: [199, 201, 203, 204, 205, 207, 208, 210, 212, 214],
      tags: ["Sector leadership", "Clean trend"]
    },
    {
      symbol: "JPM",
      name: "JPMorgan Chase & Co.",
      type: "stock",
      sector: "Financials",
      score: 71,
      close: 197.4,
      rsi14: 59,
      volumeRatio: 1.08,
      return20: 4.7,
      above50: true,
      above100: true,
      above200: true,
      recentCross: false,
      relativeStrength: 2.4,
      history: [184, 185, 186, 188, 190, 191, 193, 194, 196, 197],
      tags: ["Rates sensitive", "Financial leadership"]
    }
  ],
  macro: [
    { label: "10Y Treasury", value: "4.58%", delta: "+7 bps" },
    { label: "2Y Treasury", value: "4.94%", delta: "+5 bps" },
    { label: "Fed Funds", value: "5.33%", delta: "Flat" },
    { label: "Unemployment", value: "3.9%", delta: "+0.1 pp" },
    { label: "CPI YoY", value: "3.5%", delta: "+0.3 pp" },
    { label: "GDP QoQ", value: "1.6%", delta: "-1.8 pp" }
  ],
  calendar: [
    { date: "2026-05-08", time: "8:30 AM ET", event: "Employment Situation", source: "BLS", importance: "High" },
    { date: "2026-05-13", time: "8:30 AM ET", event: "Consumer Price Index", source: "BLS", importance: "High" },
    { date: "2026-05-29", time: "8:30 AM ET", event: "Personal Income and Outlays", source: "BEA", importance: "High" },
    { date: "2026-06-17", time: "2:00 PM ET", event: "FOMC Rate Decision", source: "Federal Reserve", importance: "High" }
  ],
  sources: []
};

const state = {
  snapshot: fallbackSnapshot,
  activeView: "briefing",
  scorebook: {
    status: "loading",
    generatedAt: null,
    asOfDate: null,
    rows: [],
    rowCount: 0,
    returnNotes: "",
    query: "",
    sector: "",
    sortKey: "modelScore",
    sortDirection: "desc"
  },
  monitoring: {
    status: "loading",
    generatedAt: null,
    asOfDate: null,
    rowCount: 0,
    topDecileCutoff: 0,
    topDecileCount: 0,
    recentEntrantCount: 0,
    trailingReturnStatus: "",
    marketDataStatus: null,
    currentTopDecile: [],
    recentEntrants: [],
    methodology: []
  },
  tickerLab: {
    enabled: true,
    apiReady: false,
    apiBaseUrl: "",
    requiresAccessCode: false,
    loading: false,
    status: "",
    result: null,
    error: null,
    maxTickers: 25
  }
};

const $ = (selector) => document.querySelector(selector);

function on(selector, eventName, handler) {
  const element = $(selector);
  if (element) element.addEventListener(eventName, handler);
}

function esc(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&#39;");
}

function formatDate(value) {
  return new Intl.DateTimeFormat("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit"
  }).format(new Date(value));
}

function formatShortDate(value) {
  if (!value) return "Date unavailable";
  const date = /^\d{4}-\d{2}-\d{2}$/.test(String(value)) ? new Date(`${value}T12:00:00`) : new Date(value);
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric"
  }).format(date);
}

function pct(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) return "n/a";
  return `${number >= 0 ? "+" : ""}${number.toFixed(2)}%`;
}

function displayPct(value) {
  if (!Number.isFinite(Number(value))) return "n/a";
  return pct(value);
}

function displayScore(value) {
  if (!Number.isFinite(Number(value))) return "n/a";
  return Number(value).toFixed(6);
}

function displayMarketCap(value, fallbackText) {
  if (fallbackText) return fallbackText;
  const number = Number(value);
  if (!Number.isFinite(number)) return "n/a";
  if (number >= 1_000_000_000_000) return `$${(number / 1_000_000_000_000).toFixed(2)}T`;
  if (number >= 1_000_000_000) return `$${(number / 1_000_000_000).toFixed(1)}B`;
  if (number >= 1_000_000) return `$${(number / 1_000_000).toFixed(1)}M`;
  return `$${number.toLocaleString("en-US")}`;
}

function returnClass(value) {
  if (!Number.isFinite(Number(value))) return "";
  return Number(value) < 0 ? "negative" : "positive";
}

function hasModelRank(item) {
  return Number.isFinite(Number(item?.modelRank));
}

function sortedSourceArticles() {
  return (state.snapshot.sources || [])
    .flatMap((source) => (source.articles || []).map((article) => ({ ...article, sourceName: article.sourceName || source.name })))
    .filter((article) => article.title && article.url)
    .filter((article) => !/(pardon our interruption|privacy|terms|sign in|login|subscribe)/i.test(`${article.title} ${article.summary || ""}`))
    .sort((a, b) => {
      const aTime = a.publishedAt ? new Date(a.publishedAt).getTime() : 0;
      const bTime = b.publishedAt ? new Date(b.publishedAt).getTime() : 0;
      if (aTime !== bTime) return bTime - aTime;
      return String(a.title || "").localeCompare(String(b.title || ""));
    })
    .slice(0, 36);
}

function sourceRefMap() {
  const map = new Map(sortedSourceArticles().map((article, index) => [`S${index + 1}`, article]));
  (state.snapshot.marketIntelligence?.officialMacro?.releases || []).forEach((release) => {
    if (!release.id) return;
    map.set(release.id, {
      sourceName: release.sourceName,
      title: release.title || release.event,
      url: release.sourceUrl,
      publishedAt: release.publishedAt || release.releaseAt,
      summary: release.marketRead
    });
  });
  return map;
}

function compactSourceName(value) {
  return String(value || "")
    .replace(/\s*\|\s*.*/, "")
    .replace(/\s*-\s*.*$/, "")
    .replace(/\s+Research$/, "")
    .trim();
}

function sourceRefLabel(ref, symbol, researchSources) {
  const research = String(ref).match(/^S(\d+)$/);
  if (research) {
    const article = researchSources.get(ref);
    return compactSourceName(article?.sourceName) || `Research Source ${research[1]}`;
  }

  const officialMacro = String(ref).match(/^O(\d+)$/);
  if (officialMacro) {
    const release = researchSources.get(ref);
    return compactSourceName(release?.sourceName) || `Official Macro ${officialMacro[1]}`;
  }

  const companyRef = String(ref).match(/^C\d+-(N\d+|IR|MARKETCAP|EARNINGS)$/);
  if (!companyRef) return ref;

  const prefix = symbol ? `${symbol} ` : "";
  if (companyRef[1].startsWith("N")) return `${prefix}News`;
  if (companyRef[1] === "IR") return `${prefix}Investor Relations`;
  if (companyRef[1] === "MARKETCAP") return `${prefix}Market Cap`;
  if (companyRef[1] === "EARNINGS") return `${prefix}Earnings`;
  return ref;
}

function sourceRefLabels(refs, symbol, researchSources) {
  return [...new Set((refs || []).map((ref) => sourceRefLabel(ref, symbol, researchSources)).filter(Boolean))];
}

function parseTickerInput(value) {
  return [
    ...new Set(
      String(value || "")
        .replace(/[,\n\r\t;]+/g, " ")
        .split(/\s+/)
        .map((token) => token.trim().toUpperCase().replace(/^\$/, ""))
        .filter(Boolean)
        .filter((token) => /^[A-Z0-9][A-Z0-9.^=\-]{0,18}$/.test(token))
    )
  ].slice(0, state.tickerLab.maxTickers || 25);
}

function normalizeApiBaseUrl(value) {
  return String(value || "").trim().replace(/\/+$/, "");
}

function tickerLabUrl(path) {
  const baseUrl = normalizeApiBaseUrl(state.tickerLab.apiBaseUrl);
  return `${baseUrl}${path}`;
}

function outlookForTicker(item) {
  if (item.setupType === "model_rebound_watch") return "Rebound Watch";
  if (item.setupTags?.includes("Not Momentum Confirmed")) return "Not Momentum";
  const percentile = Number(item.sp500Percentile ?? item.modelPercentile ?? 0);
  const riskCount = item.riskFlags?.length || 0;
  if (percentile >= 80 && riskCount <= 1 && item.above50 && item.above200) return "Favorable";
  if (percentile >= 45 && riskCount <= 2) return "Mixed";
  return "Weak";
}

function tickerNarrative(item) {
  const rank = item.sp500Rank ? `#${item.sp500Rank} of ${item.sp500UniverseCount}` : `#${item.modelRank} of ${item.modelUniverseCount}`;
  const trend = item.above50 && item.above200 ? "above both 50-day and 200-day trend lines" : item.above200 ? "above the 200-day trend line but missing shorter-term confirmation" : "below at least one major trend line";
  const relative = Number.isFinite(Number(item.relativeReturn60VsSpy)) ? `${pct(item.relativeReturn60VsSpy)} over 60 days versus SPY` : "relative-strength data is unavailable";
  const activation = item.setupType === "model_rebound_watch" && hasNumericValue(item.reboundActivationPrice)
    ? ` Rebound activation requires a close above ${money(item.reboundActivationPrice)} within ${item.reboundActivationWindowDays || 5} trading days.`
    : "";
  const setup = item.setupType === "model_rebound_watch"
    ? " This is a model rebound watch, not a confirmed momentum setup."
    : "";
  return `${item.symbol} ranks ${rank} versus the S&P 500 reference universe, with ${relative}; it is ${trend}.${setup}${activation}`;
}

function money(value) {
  if (!Number.isFinite(Number(value))) return "n/a";
  return Number(value).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: Number(value) > 100 ? 2 : 2
  });
}

function hasNumericValue(value) {
  return value !== null && value !== undefined && value !== "" && Number.isFinite(Number(value));
}

function stopSellForSymbol(symbol) {
  const direct = (state.snapshot.recommendations || []).find((item) => item.symbol === symbol && hasNumericValue(item.stopSellPrice));
  if (direct) return direct;
  return (state.snapshot.opportunities || []).find(
    (item) => item.symbol === symbol && hasNumericValue(item.stopSellPrice)
  );
}

function stopSellChip(item) {
  const stop = hasNumericValue(item?.stopSellPrice) ? item : stopSellForSymbol(item?.symbol);
  if (!stop || !hasNumericValue(stop.stopSellPrice)) return "";
  const distance = hasNumericValue(stop.stopSellDistancePct) ? ` · ${pct(stop.stopSellDistancePct)}` : "";
  return `<span class="stop-chip" title="Exit on end-of-day close below stop">Stop: ${money(stop.stopSellPrice)}${distance}</span>`;
}

function activationChip(item) {
  if (item?.setupType !== "model_rebound_watch" || !hasNumericValue(item.reboundActivationPrice)) return "";
  const windowDays = item.reboundActivationWindowDays || 5;
  return `<span class="stop-chip activation-chip" title="Requires an end-of-day close above this level within ${esc(windowDays)} trading days">Activation: ${money(item.reboundActivationPrice)}</span>`;
}

function renderList(target, items) {
  target.innerHTML = "";
  items.forEach((item) => {
    const li = document.createElement("li");
    li.textContent = item;
    target.appendChild(li);
  });
}

function sparkline(values) {
  const width = 320;
  const height = 52;
  const clean = values.filter((value) => Number.isFinite(Number(value))).map(Number);
  if (clean.length < 2) return "";
  const min = Math.min(...clean);
  const max = Math.max(...clean);
  const span = max - min || 1;
  const step = width / (clean.length - 1);
  const points = clean
    .map((value, index) => {
      const x = index * step;
      const y = height - ((value - min) / span) * (height - 8) - 4;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(" ");
  return `
    <svg class="spark" viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" aria-hidden="true">
      <polyline points="${points}" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"></polyline>
    </svg>
  `;
}

function renderMarketStrip() {
  const strip = $("#marketStrip");
  strip.innerHTML = "";
  state.snapshot.marketStrip.slice(0, 6).forEach((item) => {
    const tile = document.createElement("div");
    tile.className = "ticker-tile";
    tile.innerHTML = `
      <span>${esc(item.label || item.symbol)}</span>
      <strong>${esc(item.symbol)} ${money(item.price)}</strong>
      <em class="${Number(item.changePct) < 0 ? "negative" : ""}">${pct(item.changePct)}</em>
    `;
    strip.appendChild(tile);
  });
}

function renderNote() {
  const note = state.snapshot.note || fallbackSnapshot.note;
  $("#asOfDate").textContent = `As of ${formatDate(state.snapshot.generatedAt)}`;
  $("#noteHeadline").textContent = note.headline;
  $("#noteBody").textContent = note.body;
  renderDataStatusBanner();
  renderMarketIntelligence();
  renderList($("#changedList"), note.changed || []);
  renderList($("#watchList"), note.watch || []);
}

function renderDataStatusBanner() {
  const banner = $("#dataStatusBanner");
  if (!banner) return;
  const messages = [];
  const marketStatus = state.snapshot.marketDataStatus;
  const model = state.snapshot.model || {};

  if (marketStatus?.status && marketStatus.status !== "fresh") {
    messages.push(marketStatus.message || "Fresh price and technical data is unavailable; stale cached technical data is not shown.");
  }
  if (model.isStale) {
    messages.push(`Model rankings are stale: as of ${model.asOfDate || "unknown"}, expected ${model.expectedAsOfDate || "current market date"}. Stale model ranks were not used.`);
  } else if (model.status && model.status !== "ready") {
    messages.push(model.unavailableReason || "Model rankings are unavailable for this snapshot.");
  }

  banner.hidden = messages.length === 0;
  banner.innerHTML = messages.map((message) => `<span>${esc(message)}</span>`).join("");
}

function intelItemLink(item, title) {
  const safeTitle = esc(title || item.title || item.symbol || "Market item");
  return item.url
    ? `<a href="${esc(item.url)}" target="_blank" rel="noreferrer">${safeTitle}</a>`
    : `<strong>${safeTitle}</strong>`;
}

function renderIntelStack(target, items, emptyText, renderer) {
  target.innerHTML = "";
  if (!items.length) {
    target.innerHTML = `<div class="empty-state">${esc(emptyText)}</div>`;
    return;
  }
  items.forEach((item) => {
    const card = document.createElement("article");
    card.className = "intel-item";
    card.innerHTML = renderer(item);
    target.appendChild(card);
  });
}

function renderMarketIntelligence() {
  const intel = state.snapshot.marketIntelligence || fallbackSnapshot.marketIntelligence;
  const officialMacro = (intel.officialMacro?.releases || [])
    .filter((item) => item.status === "ready")
    .slice(0, 3)
    .map((item) => ({
      ...item,
      title: item.title || item.event,
      url: item.sourceUrl,
      freshness: "Official macro release",
      summary: item.marketRead
    }));
  const drivers = [...officialMacro, ...(intel.professionalDrivers || [])].slice(0, 5);
  const earningsMovers = (intel.earnings?.earningsMovers || []).slice(0, 5);
  const redditTickers = (intel.reddit?.topTickers || []).slice(0, 5);

  renderIntelStack(
    $("#marketDriverList"),
    drivers,
    "No fresh professional market-driver items were extracted in this snapshot.",
    (item) => `
      ${intelItemLink(item)}
      <span>${esc((item.themes || []).slice(0, 2).join(" / ") || "Market driver")} · ${esc(item.sourceName || "")}</span>
      <small>${esc(item.freshness || "")}${item.publishedAt ? ` · ${esc(formatShortDate(item.publishedAt))}` : ""}</small>
    `
  );

  renderIntelStack(
    $("#earningsMoverList"),
    earningsMovers,
    "No large daily mover matched the earnings calendar in this snapshot.",
    (item) => `
      ${intelItemLink(item, `${item.symbol} ${pct(item.changePct)}`)}
      <span>${esc(item.name || "")}</span>
      <small>${esc(item.moverBucket || "mover")} · ${esc(item.sourceName || "Nasdaq / Yahoo Finance")}</small>
    `
  );

  renderIntelStack(
    $("#redditAttentionList"),
    redditTickers,
    "No clean Reddit ticker concentration was extracted in this snapshot.",
    (item) => `
      <strong>${esc(item.symbol)}</strong>
      <span>${esc(item.mentions || 0)} mentions · ${esc(item.comments || 0)} comments · ${esc((item.subreddits || []).join(", "))}</span>
      <small>Retail sentiment only; not verified news.</small>
    `
  );
}

function renderDeeperRead() {
  const deeper = state.snapshot.deeperRead || state.snapshot.aiRecommendations?.deeperRead || fallbackSnapshot.deeperRead;
  const list = $("#deeperReadList");
  const summary = $("#deeperReadSummary");
  const meta = $("#deeperReadMeta");
  const researchSources = sourceRefMap();
  const cards = deeper.cards || [];

  meta.textContent = `${deeper.lookbackDays || 7}-day source lens`;
  summary.textContent = deeper.summary || "No differentiated source analysis cleared the quality filter in this snapshot.";
  list.innerHTML = "";

  if (!cards.length) {
    list.innerHTML = `<div class="empty-state">No Deeper Read cards were generated for this refresh.</div>`;
    return;
  }

  cards.forEach((item) => {
    const refLabels = sourceRefLabels(item.sourceRefs || [item.sourceRef], null, researchSources);
    const card = document.createElement("article");
    card.className = "deeper-card";
    const source = item.url
      ? `<a href="${esc(item.url)}" target="_blank" rel="noreferrer">${esc(item.sourceName || "Source")}</a>`
      : `<span>${esc(item.sourceName || "Source")}</span>`;
    card.innerHTML = `
      <header>
        <div>
          <span>${source}${item.publishedAt ? ` · ${esc(formatShortDate(item.publishedAt))}` : ""}</span>
          <strong>${esc(item.title || "Research angle")}</strong>
        </div>
        <em>${esc(item.confidence || "Review")}</em>
      </header>
      <p>${esc(item.thesis || "")}</p>
      <div class="deeper-card-body">
        <small><strong>Why it matters:</strong> ${esc(item.whyItMatters || "")}</small>
        <small><strong>Market read-through:</strong> ${esc(item.marketReadThrough || "")}</small>
        <small><strong>Variant angle:</strong> ${esc(item.variantAngle || "")}</small>
      </div>
      ${refLabels.length ? `<div class="source-ref-row">${refLabels.map((label) => `<span>${esc(label)}</span>`).join("")}</div>` : ""}
    `;
    list.appendChild(card);
  });
}

function renderRecommendations() {
  const list = $("#recommendationList");
  const recommendations = state.snapshot.recommendations || [];
  list.innerHTML = "";

  if (!recommendations.length) {
    list.innerHTML = `<div class="empty-state">No desk calls are available in this snapshot.</div>`;
    return;
  }

  recommendations.slice(0, 6).forEach((item) => {
    const labelClass = item.label === "RSI Above Limit" || item.label === "Model Risk Check" ? "risk" : item.label === "Near Threshold" ? "watch" : "";
    const card = document.createElement("article");
    card.className = "recommendation";
    card.innerHTML = `
      <span class="rec-label ${labelClass}">${esc(item.label)}</span>
      <strong>${esc(item.symbol)} · ${esc(item.title)}</strong>
      ${stopSellChip(item)}
      <p>${esc(item.rationale)}</p>
    `;
    list.appendChild(card);
  });
}

function renderAiRecommendations() {
  const ai = state.snapshot.aiRecommendations || fallbackSnapshot.aiRecommendations;
  const cost = ai.usage?.estimatedCostUsd;
  const modelSummary = state.snapshot.model;
  const modelText = modelSummary?.status === "ready" ? ` · ${modelSummary.scoredCount} model-scored` : "";
  const researchSources = sourceRefMap();
  $("#aiMeta").textContent =
    ai.status === "ready"
      ? `Generated by ${ai.model || "AI"}${Number.isFinite(cost) ? ` · ~$${cost.toFixed(4)}` : ""}${modelText}`
      : "Configure OPENAI_API_KEY";
  $("#aiHeadline").textContent = ai.headline || "AI synthesis unavailable";
  $("#aiMacroView").textContent = ai.macroView || "";

  const list = $("#aiRecommendationList");
  list.innerHTML = "";

  if (!ai.recommendations?.length) {
    list.innerHTML = `<div class="empty-state">Run the refresh with OPENAI_API_KEY to generate macro-aware AI calls.</div>`;
  } else {
    ai.recommendations.slice(0, 6).forEach((item) => {
      const card = document.createElement("article");
      card.className = "ai-rec";
      const setup = item.setup || item.rationale || "";
      const whyNow = item.whyNow || item.macroLink || "";
      const companyOverview = item.companyOverview || "";
      const marketCap = item.marketCap || item.marketCapText || "";
      const earningsContext = item.earningsContext || "";
      const recentNews = item.recentNews || "";
      const macroEvidence = item.macroEvidence || item.macroLink || "";
      const modelEvidence = item.modelEvidence || "";
      const technicalEvidence = item.technicalEvidence || item.momentumEvidence || "";
      const invalidation = item.invalidation || "";
      const setupTags = Array.isArray(item.setupTags) ? item.setupTags : [];
      const refLabels = sourceRefLabels(item.sourceRefs, item.symbol, researchSources);
      card.innerHTML = `
        <header>
          <div>
            <strong>${esc(item.symbol)} · ${esc(item.action)}</strong>
            <small>${esc(whyNow)}</small>
          </div>
          <span class="conviction">${esc(item.conviction || "Review")}</span>
        </header>
        <p>${esc(setup)}</p>
        ${setupTags.length ? `<div class="tags">${setupTags.map((tag) => `<span class="tag">${esc(tag)}</span>`).join("")}</div>` : ""}
        ${
          companyOverview || marketCap || earningsContext || recentNews
            ? `<div class="company-context">
                ${companyOverview ? `<small><strong>Company:</strong> ${esc(companyOverview)}</small>` : ""}
                ${marketCap ? `<small><strong>Market Cap:</strong> ${esc(marketCap)}</small>` : ""}
                ${earningsContext ? `<small><strong>Earnings:</strong> ${esc(earningsContext)}</small>` : ""}
                ${recentNews ? `<small><strong>News:</strong> ${esc(recentNews)}</small>` : ""}
              </div>`
            : ""
        }
        <div class="ai-evidence">
          <small><strong>Macro:</strong> ${esc(macroEvidence)}</small>
          ${modelEvidence ? `<small><strong>Model:</strong> ${esc(modelEvidence)}</small>` : ""}
          <small><strong>Technical:</strong> ${esc(technicalEvidence)}</small>
        </div>
        <small><strong>Risk:</strong> ${esc(item.risk || "")}</small>
        ${invalidation ? `<small><strong>Invalidation:</strong> ${esc(invalidation)}</small>` : ""}
        ${refLabels.length ? `<div class="source-ref-row">${refLabels.map((label) => `<span>${esc(label)}</span>`).join("")}</div>` : ""}
      `;
      list.appendChild(card);
    });
  }

  renderList($("#aiPortfolioNotes"), ai.portfolioNotes || []);
  renderList($("#aiOpenQuestions"), ai.openQuestions || []);
}

function renderAvoidList() {
  const avoid = state.snapshot.avoidList || fallbackSnapshot.avoidList;
  const sectorsTarget = $("#avoidSectors");
  const companiesTarget = $("#avoidList");
  $("#avoidSummary").textContent = avoid.summary || "Lowest-ranked model names are unavailable in this snapshot.";
  sectorsTarget.innerHTML = "";
  companiesTarget.innerHTML = "";

  const sectors = avoid.sectors || [];
  if (sectors.length) {
    sectors.slice(0, 4).forEach((item) => {
      const card = document.createElement("article");
      card.className = "avoid-sector";
      const examples = item.examples?.length ? `Examples: ${item.examples.join(", ")}` : "";
      card.innerHTML = `
        <span>${esc(item.count != null ? `${item.count} bottom names` : "Bottom-ranked cluster")}</span>
        <strong>${esc(item.sector || "Sector review")}</strong>
        <p>${esc(item.rationale || examples)}</p>
      `;
      sectorsTarget.appendChild(card);
    });
  }

  const companies = avoid.companies || [];
  if (!companies.length) {
    companiesTarget.innerHTML = `<div class="empty-state">Run the model refresh to populate lowest-ranked companies.</div>`;
    return;
  }

  companies.slice(0, 8).forEach((item) => {
    const card = document.createElement("article");
    card.className = "avoid-card";
    const meta = [item.sector, item.marketCap].filter(Boolean).join(" · ");
    const evidence = item.modelEvidence || item.rationale || item.reason || "Lowest-ranked by the model.";
    const risk = Array.isArray(item.riskFlags) ? item.riskFlags.join("; ") : item.risk || item.riskFlags || "";
    card.innerHTML = `
      <header>
        <div>
          <strong>${esc(item.symbol)}</strong>
          <span>${esc(item.name || meta || "Model-ranked company")}</span>
        </div>
        <span class="avoid-rank">#${esc(item.modelRank || "-")}</span>
      </header>
      ${meta ? `<small>${esc(meta)}</small>` : ""}
      <p>${esc(evidence)}</p>
      ${risk ? `<small><strong>Risk flags:</strong> ${esc(risk)}</small>` : ""}
    `;
    companiesTarget.appendChild(card);
  });
}

function renderSectorPerformance() {
  const grid = $("#sectorGrid");
  const sectors = state.snapshot.sectorPerformance || [];
  grid.innerHTML = "";

  if (!sectors.length) {
    grid.innerHTML = `<div class="empty-state">Run the refresh script to populate sector performance.</div>`;
    return;
  }

  sectors.forEach((item) => {
    const tile = document.createElement("article");
    tile.className = "sector-tile";
    const trendTags = [
      item.above50 ? "Above 50D" : "Below 50D",
      item.above200 ? "Above 200D" : "Below 200D",
      Number(item.relative30d) >= 0 ? "30D > SPY" : "30D < SPY",
      Number(item.rsi14) > 76 ? "RSI > 76" : `RSI ${Math.round(item.rsi14 || 0)}`
    ];
    tile.innerHTML = `
      <div class="sector-head">
        <div>
          <strong>${esc(item.sector)}</strong>
          <span>${esc(item.symbol)}</span>
        </div>
        <span class="conviction">${pct(item.change30d)}</span>
      </div>
      ${sparkline(item.history || [])}
      <div class="sector-main">
        <div><span>30D</span><strong>${pct(item.change30d)}</strong></div>
        <div><span>YTD</span><strong>${pct(item.ytd)}</strong></div>
      </div>
      <div class="sector-mini">
        <div><span>1D</span><strong>${pct(item.change1d)}</strong></div>
        <div><span>5D</span><strong>${pct(item.change5d)}</strong></div>
        <div><span>vs SPY 30D</span><strong>${pct(item.relative30d)}</strong></div>
      </div>
      <div class="sector-badges">${trendTags.map((tag) => `<span class="tag">${esc(tag)}</span>`).join("")}</div>
    `;
    grid.appendChild(tile);
  });
}

function renderOpportunities() {
  const list = $("#opportunityList");
  const matches = [...state.snapshot.opportunities]
    .sort((a, b) => {
      const aModel = hasModelRank(a);
      const bModel = hasModelRank(b);
      if (aModel && bModel) return Number(a.modelRank) - Number(b.modelRank);
      if (aModel !== bModel) return aModel ? -1 : 1;
      return b.score - a.score;
    })
    .slice(0, 18);

  $("#bookMeta").textContent =
    state.snapshot.model?.status === "ready"
      ? `${state.snapshot.model.scoredCount} model-scored · ${state.snapshot.opportunities.length} screened`
      : `${state.snapshot.opportunities.length} screened`;
  list.innerHTML = "";

  if (!matches.length) {
    list.innerHTML = `<div class="empty-state">No momentum names are available in this snapshot.</div>`;
    return;
  }

  matches.forEach((item) => {
    const article = document.createElement("article");
    article.className = "opportunity";
    const modelRanked = hasModelRank(item);
    const badges = [...new Set([
      ...(item.setupTags || []),
      ...(modelRanked ? item.modelReasons || [] : []),
      ...(item.tags || []),
      ...(item.riskFlags || [])
    ])].slice(0, 6);
    article.innerHTML = `
      <div class="opp-head">
        <div>
          <strong>${esc(item.symbol)}</strong>
          <span>${esc(item.name || item.sector || item.type)}</span>
        </div>
        <div class="score ${modelRanked ? "model-score" : ""}">
          ${modelRanked ? `<span>#${esc(item.modelRank)}</span><small>${Number(item.modelPercentile || 0).toFixed(0)}%</small>` : Math.round(item.score)}
        </div>
      </div>
      <div class="setup-chips">${stopSellChip(item)}${activationChip(item)}</div>
      ${sparkline(item.history || [])}
      <div class="signal-grid">
        <div><span>Close</span><strong>${money(item.close)}</strong></div>
        <div><span>${modelRanked ? "60D vs SPY" : "20D return"}</span><strong>${pct(modelRanked ? item.relativeReturn60VsSpy : item.return20)}</strong></div>
        <div><span>RSI 14</span><strong>${Number(item.rsi14 || 0).toFixed(0)}</strong></div>
      </div>
      <div class="tags">${badges.map((tag) => `<span class="tag">${esc(tag)}</span>`).join("")}</div>
    `;
    list.appendChild(article);
  });
}

function renderTickerLab() {
  const panel = $("#ticker-lab");
  const nav = $("#tickerLabNav");
  if (!panel) return;

  panel.hidden = false;
  if (nav) nav.hidden = false;

  const submit = $("#tickerLabSubmit");
  const status = $("#tickerLabStatus");
  const meta = $("#tickerLabMeta");
  const results = $("#tickerLabResults");
  const tokenInput = $("#tickerLabToken");
  const tokenLabel = $("#tickerLabTokenLabel");
  const ready = state.tickerLab.apiReady;
  submit.disabled = state.tickerLab.loading || !ready;
  meta.textContent = state.tickerLab.loading
    ? "Scoring model"
    : ready
      ? state.tickerLab.requiresAccessCode
        ? "Private API"
        : "Model API ready"
      : "Backend offline";
  if (tokenInput && tokenLabel) {
    tokenInput.hidden = !state.tickerLab.requiresAccessCode;
    tokenLabel.hidden = !state.tickerLab.requiresAccessCode;
  }
  status.textContent =
    state.tickerLab.status ||
    (ready
      ? `Paste up to ${state.tickerLab.maxTickers} symbols separated by spaces, commas, or lines.`
      : "Ticker Lab is visible here, but scoring needs the private model backend URL configured.");
  results.innerHTML = "";

  if (state.tickerLab.error) {
    results.innerHTML = `<div class="empty-state">${esc(state.tickerLab.error)}</div>`;
    return;
  }

  const payload = state.tickerLab.result;
  if (!payload) return;

  const summary = document.createElement("div");
  summary.className = "ticker-lab-summary";
  summary.innerHTML = `
    <strong>${esc(payload.results?.length || 0)} scored</strong>
    <span>As of ${esc(payload.asOfDate || "latest close")} · ${esc(payload.referenceUniverse || "S&P 500")} (${esc(payload.referenceUniverseCount || 0)} names)</span>
  `;
  results.appendChild(summary);

  if (payload.unscoredSymbols?.length || Object.keys(payload.failures || {}).length) {
    const warning = document.createElement("div");
    warning.className = "empty-state";
    const failures = Object.entries(payload.failures || {}).map(([symbol, error]) => `${symbol}: ${error}`);
    warning.textContent = [
      payload.unscoredSymbols?.length ? `Unscored: ${payload.unscoredSymbols.join(", ")}` : "",
      failures.length ? `Failures: ${failures.join(" | ")}` : ""
    ].filter(Boolean).join(" ");
    results.appendChild(warning);
  }

  const grid = document.createElement("div");
  grid.className = "ticker-result-grid";
  (payload.results || []).forEach((item) => {
    const card = document.createElement("article");
    card.className = "ticker-result";
    const outlook = outlookForTicker(item);
    const sectorNote =
      item.sectorSource === "return_correlation"
        ? `${item.sector} proxy via ${item.sectorEtf}; ${Number(item.sectorCorrelation || 0).toFixed(2)} correlation`
        : item.sector || "Sector unavailable";
    card.innerHTML = `
      <header>
        <div>
          <strong>${esc(item.symbol)}</strong>
          <span>${esc(item.name || item.symbol)}</span>
        </div>
        <span class="conviction">${esc(outlook)}</span>
      </header>
      <div class="setup-chips">${activationChip(item)}</div>
      <p>${esc(tickerNarrative(item))}</p>
      <div class="signal-grid">
        <div><span>S&P rank</span><strong>#${esc(item.sp500Rank || item.modelRank)} / ${esc(item.sp500UniverseCount || item.modelUniverseCount)}</strong></div>
        <div><span>Percentile</span><strong>${Number(item.sp500Percentile ?? item.modelPercentile ?? 0).toFixed(1)}%</strong></div>
        <div><span>60D vs SPY</span><strong>${pct(item.relativeReturn60VsSpy)}</strong></div>
        <div><span>RSI 14</span><strong>${Number(item.rsi14 || 0).toFixed(0)}</strong></div>
      </div>
      <small><strong>Sector context:</strong> ${esc(sectorNote)}</small>
      <small><strong>Model score:</strong> ${Number(item.modelScore || 0).toFixed(6)} · <strong>Close:</strong> ${money(item.close)}</small>
      ${[...(item.setupTags || []), ...(item.modelReasons || [])].length ? `<div class="tags">${[...(item.setupTags || []), ...(item.modelReasons || [])].map((tag) => `<span class="tag">${esc(tag)}</span>`).join("")}</div>` : ""}
      ${item.riskFlags?.length ? `<small><strong>Risk flags:</strong> ${esc(item.riskFlags.join("; "))}</small>` : ""}
    `;
    grid.appendChild(card);
  });
  results.appendChild(grid);

  if (payload.methodologyNotes?.length) {
    const notes = document.createElement("div");
    notes.className = "methodology-notes";
    notes.innerHTML = `<h3>Methodology Notes</h3><ul>${payload.methodologyNotes.map((note) => `<li>${esc(note)}</li>`).join("")}</ul>`;
    results.appendChild(notes);
  }
}

function scorebookSortValue(row, key) {
  const value = row?.[key];
  if (
    ["modelRank", "marketCapValue", "modelScore", "modelPercentile", "beta60d", "return7", "return14", "return30", "return60", "return90", "ytdReturn"].includes(key)
  ) {
    return Number.isFinite(Number(value)) ? Number(value) : null;
  }
  return String(value || "").toLowerCase();
}

function compareScorebookRows(a, b) {
  const { sortKey, sortDirection } = state.scorebook;
  const direction = sortDirection === "asc" ? 1 : -1;
  const aValue = scorebookSortValue(a, sortKey);
  const bValue = scorebookSortValue(b, sortKey);
  if (aValue == null && bValue == null) return String(a.symbol).localeCompare(String(b.symbol));
  if (aValue == null) return 1;
  if (bValue == null) return -1;
  if (typeof aValue === "number" && typeof bValue === "number") {
    if (aValue !== bValue) return (aValue - bValue) * direction;
  } else {
    const comparison = String(aValue).localeCompare(String(bValue));
    if (comparison !== 0) return comparison * direction;
  }
  return Number(a.modelRank || 9999) - Number(b.modelRank || 9999);
}

function filteredScorebookRows() {
  const query = state.scorebook.query.trim().toLowerCase();
  const sector = state.scorebook.sector;
  return (state.scorebook.rows || [])
    .filter((row) => !sector || row.sector === sector)
    .filter((row) => {
      if (!query) return true;
      return [row.symbol, row.name, row.sector, row.industry, ...(row.setupTags || [])].some((value) => String(value || "").toLowerCase().includes(query));
    })
    .sort(compareScorebookRows);
}

function renderScorebookSectorOptions() {
  const select = $("#scoreboardSector");
  if (!select) return;
  const sectors = [...new Set((state.scorebook.rows || []).map((row) => row.sector).filter(Boolean))].sort((a, b) => a.localeCompare(b));
  const signature = sectors.join("|");
  if (select.dataset.signature === signature) return;
  select.dataset.signature = signature;
  select.innerHTML = `<option value="">All sectors</option>${sectors.map((sector) => `<option value="${esc(sector)}">${esc(sector)}</option>`).join("")}`;
  select.value = state.scorebook.sector;
}

function renderScorebookSortState() {
  document.querySelectorAll("[data-score-sort]").forEach((button) => {
    const active = button.dataset.scoreSort === state.scorebook.sortKey;
    button.classList.toggle("active", active);
    button.dataset.direction = active ? state.scorebook.sortDirection : "";
  });
}

function renderScoreboard() {
  const tbody = $("#scoreboardRows");
  const meta = $("#scoreboardMeta");
  if (!tbody || !meta) return;

  renderScorebookSectorOptions();
  renderScorebookSortState();

  const rows = filteredScorebookRows();
  const total = state.scorebook.rowCount || state.scorebook.rows.length;
  const asOf = state.scorebook.asOfDate ? formatShortDate(state.scorebook.asOfDate) : "latest close";
  const notes = state.scorebook.returnNotes ? ` · ${state.scorebook.returnNotes}` : "";
  meta.textContent =
    state.scorebook.status === "ready"
      ? `${rows.length}/${total} rows · as of ${asOf}${notes}`
      : "Model scoreboard unavailable";

  if (!rows.length) {
    tbody.innerHTML = `
      <tr>
        <td colspan="14">${state.scorebook.status === "ready" ? "No rows match the current filter." : "Run the daily refresh to populate the model scoreboard."}</td>
      </tr>
    `;
    return;
  }

  tbody.innerHTML = rows
    .map(
      (row) => `
        <tr>
          <td><span class="score-rank">#${esc(row.modelRank || "-")}</span></td>
          <td>
            <strong>${esc(row.symbol)}</strong>
            <span>${esc(row.sector || "Unclassified")}</span>
            ${row.setupTags?.length ? `<small class="scoreboard-setup">${esc(row.setupTags[0])}</small>` : ""}
            ${row.setupType === "model_rebound_watch" && hasNumericValue(row.reboundActivationPrice) ? `<small class="scoreboard-activation">Activation ${money(row.reboundActivationPrice)}</small>` : ""}
            ${hasNumericValue(row.stopSellPrice) ? `<small class="scoreboard-activation stop-cell">Stop ${money(row.stopSellPrice)}</small>` : ""}
          </td>
          <td>${esc(row.name || row.symbol)}</td>
          <td>${esc(row.industry || "n/a")}</td>
          <td>${esc(displayMarketCap(row.marketCapValue, row.marketCap))}</td>
          <td>${esc(displayScore(row.modelScore))}</td>
          <td>${Number.isFinite(Number(row.modelPercentile)) ? `${Number(row.modelPercentile).toFixed(1)}%` : "n/a"}</td>
          <td>${Number.isFinite(Number(row.beta60d)) ? Number(row.beta60d).toFixed(2) : "n/a"}</td>
          <td class="${returnClass(row.return7)}">${esc(displayPct(row.return7))}</td>
          <td class="${returnClass(row.return14)}">${esc(displayPct(row.return14))}</td>
          <td class="${returnClass(row.return30)}">${esc(displayPct(row.return30))}</td>
          <td class="${returnClass(row.return60)}">${esc(displayPct(row.return60))}</td>
          <td class="${returnClass(row.return90)}">${esc(displayPct(row.return90))}</td>
          <td class="${returnClass(row.ytdReturn)}">${esc(displayPct(row.ytdReturn))}</td>
        </tr>
      `
    )
    .join("");
}

function topDecileFromScorebook() {
  const rows = [...(state.scorebook.rows || [])].sort((a, b) => Number(a.modelRank || 9999) - Number(b.modelRank || 9999));
  const cutoff = Math.ceil(rows.length * 0.1);
  return rows.slice(0, cutoff).map((row) => ({
    ...row,
    status: "Current Top Decile",
    previousRank: null,
    oneRunRankChange: null,
    lookbackRankChange: null
  }));
}

function displayRankMove(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) return "n/a";
  if (number === 0) return "Flat";
  return number > 0 ? `+${number}` : `${number}`;
}

function rankMoveClass(value) {
  const number = Number(value);
  if (!Number.isFinite(number) || number === 0) return "";
  return number > 0 ? "positive" : "negative";
}

function topDecileStatusClass(value) {
  const text = String(value || "").toLowerCase();
  if (text.includes("entrant")) return "entrant";
  if (text.includes("upgrade")) return "upgrade";
  if (text.includes("baseline")) return "baseline";
  return "held";
}

function renderTopDecileSummary(rows, entrants) {
  const target = $("#topDecileSummary");
  if (!target) return;
  const asOf = state.monitoring.asOfDate || state.scorebook.asOfDate;
  const generatedAt = state.monitoring.generatedAt ? formatDate(state.monitoring.generatedAt) : "latest refresh";
  const rowCount = state.monitoring.rowCount || state.scorebook.rowCount || state.scorebook.rows.length;
  const cutoff = state.monitoring.topDecileCutoff || Math.ceil(rowCount * 0.1);
  const dataStatus = state.monitoring.marketDataStatus?.status || state.scorebook.status;
  target.innerHTML = `
    <div class="monitor-card">
      <span>As Of</span>
      <strong>${esc(asOf ? formatShortDate(asOf) : "Latest close")}</strong>
      <small>Generated ${esc(generatedAt)}</small>
    </div>
    <div class="monitor-card">
      <span>Top Decile</span>
      <strong>${esc(rows.length)} names</strong>
      <small>Rank #1 to #${esc(cutoff || rows.length || "n/a")} of ${esc(rowCount || "n/a")}</small>
    </div>
    <div class="monitor-card">
      <span>Recent Moves</span>
      <strong>${esc(entrants.length)} flagged</strong>
      <small>New entrants or material rank upgrades</small>
    </div>
    <div class="monitor-card">
      <span>Data Tape</span>
      <strong>${esc(dataStatus || "unknown")}</strong>
      <small>${esc(state.monitoring.trailingReturnStatus || state.scorebook.returnNotes || "Model scorebook feed")}</small>
    </div>
  `;
}

function renderTopDecileMonitor() {
  const currentBody = $("#topDecileRows");
  const entrantBody = $("#topDecileEntrantRows");
  const meta = $("#topDecileMeta");
  const countMeta = $("#topDecileCount");
  const entrantMeta = $("#topDecileEntrantMeta");
  if (!currentBody || !entrantBody || !meta) return;

  const currentRows = (state.monitoring.currentTopDecile?.length ? state.monitoring.currentTopDecile : topDecileFromScorebook())
    .sort((a, b) => Number(a.modelRank || 9999) - Number(b.modelRank || 9999));
  const recentEntrants = [...(state.monitoring.recentEntrants || [])].sort((a, b) => Number(a.modelRank || 9999) - Number(b.modelRank || 9999));
  const rowCount = state.monitoring.rowCount || state.scorebook.rowCount || state.scorebook.rows.length;
  const asOf = state.monitoring.asOfDate || state.scorebook.asOfDate;
  meta.textContent = currentRows.length
    ? `${currentRows.length}/${rowCount || "n/a"} names · as of ${asOf ? formatShortDate(asOf) : "latest close"}`
    : "Top-decile monitor unavailable";
  if (countMeta) countMeta.textContent = rowCount ? `Top 10% of ${rowCount} scored names` : "Top 10% of scored universe";
  if (entrantMeta) entrantMeta.textContent = recentEntrants.length ? `${recentEntrants.length} flagged this refresh` : "Baseline until a prior refresh exists";

  renderTopDecileSummary(currentRows, recentEntrants);

  if (!recentEntrants.length) {
    entrantBody.innerHTML = `
      <tr>
        <td colspan="11">No recent entrants yet. Once the dashboard has at least one prior distinct refresh, this table will flag names newly entering the top decile or making major rank jumps.</td>
      </tr>
    `;
  } else {
    entrantBody.innerHTML = recentEntrants
      .map(
        (row) => `
          <tr>
            <td><span class="monitor-badge ${topDecileStatusClass(row.status)}">${esc(row.status || "Flagged")}</span></td>
            <td><span class="score-rank">#${esc(row.modelRank || "-")}</span></td>
            <td><strong>${esc(row.symbol)}</strong></td>
            <td>${esc(row.name || row.symbol)}</td>
            <td>${esc(row.sector || "n/a")}</td>
            <td>${esc(displayMarketCap(row.marketCapValue, row.marketCap))}</td>
            <td>${esc(displayScore(row.modelScore))}</td>
            <td>${Number.isFinite(Number(row.previousRank)) ? `#${Number(row.previousRank)}` : "n/a"}</td>
            <td class="${rankMoveClass(row.oneRunRankChange ?? row.lookbackRankChange)}">${esc(displayRankMove(row.oneRunRankChange ?? row.lookbackRankChange))}</td>
            <td class="${returnClass(row.return30)}">${esc(displayPct(row.return30))}</td>
            <td class="${returnClass(row.ytdReturn)}">${esc(displayPct(row.ytdReturn))}</td>
          </tr>
        `
      )
      .join("");
  }

  if (!currentRows.length) {
    currentBody.innerHTML = `
      <tr>
        <td colspan="13">Run the daily refresh to populate the current top-decile snapshot.</td>
      </tr>
    `;
    return;
  }

  currentBody.innerHTML = currentRows
    .map(
      (row) => `
        <tr>
          <td><span class="score-rank">#${esc(row.modelRank || "-")}</span></td>
          <td>
            <strong>${esc(row.symbol)}</strong>
            <span>${esc(row.sector || "Unclassified")}</span>
            ${row.status ? `<small class="scoreboard-setup">${esc(row.status)}</small>` : ""}
          </td>
          <td>${esc(row.name || row.symbol)}</td>
          <td>${esc(row.industry || "n/a")}</td>
          <td>${esc(displayMarketCap(row.marketCapValue, row.marketCap))}</td>
          <td>${esc(displayScore(row.modelScore))}</td>
          <td>${Number.isFinite(Number(row.modelPercentile)) ? `${Number(row.modelPercentile).toFixed(1)}%` : "n/a"}</td>
          <td>${esc(row.setupTags?.[0] || row.setupType || "n/a")}</td>
          <td>${Number.isFinite(Number(row.beta60d)) ? Number(row.beta60d).toFixed(2) : "n/a"}</td>
          <td class="${returnClass(row.return7)}">${esc(displayPct(row.return7))}</td>
          <td class="${returnClass(row.return14)}">${esc(displayPct(row.return14))}</td>
          <td class="${returnClass(row.return30)}">${esc(displayPct(row.return30))}</td>
          <td class="${returnClass(row.ytdReturn)}">${esc(displayPct(row.ytdReturn))}</td>
        </tr>
      `
    )
    .join("");
}

function renderCalendar() {
  const target = $("#calendarList");
  target.innerHTML = "";
  state.snapshot.calendar.slice(0, 8).forEach((event) => {
    const item = document.createElement("div");
    item.className = "event";
    item.innerHTML = `
      <div>
        <strong>${new Date(`${event.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</strong>
        <span>${esc(event.time || "")}</span>
      </div>
      <div>
        <strong>${esc(event.event)}</strong>
        <span>${esc(event.source || "")}</span>
        <em>${esc(event.importance || "Medium")}</em>
      </div>
    `;
    target.appendChild(item);
  });
}

function renderMacro() {
  const grid = $("#macroGrid");
  grid.innerHTML = "";
  state.snapshot.macro.slice(0, 9).forEach((item) => {
    const card = document.createElement("div");
    card.className = "macro-card";
    card.innerHTML = `<span>${esc(item.label)}</span><strong>${esc(item.value)}</strong><span>${esc(item.delta || "")}</span>`;
    grid.appendChild(card);
  });
}

function renderSources() {
  const sourceTape = $("#sourceTape");
  const allSources = state.snapshot.sources || [];
  const sources = allSources.filter((source) => source.ok && (source.articles || []).length);
  const articleCount = sources.reduce((total, source) => total + (source.articles?.length || 0), 0);
  $("#sourceCount").textContent = `${sources.length}/${allSources.length} sources · ${articleCount} recent articles`;
  sourceTape.innerHTML = "";

  if (!sources.length) {
    sourceTape.innerHTML = `<div class="empty-state">No recent dated source articles passed the freshness filter in this snapshot.</div>`;
    return;
  }

  sources.forEach((source) => {
    const item = document.createElement("div");
    item.className = "source-item";
    const articles = source.articles || [];
    item.innerHTML = `
      <div>
        <strong>${esc(source.category || "Source")}</strong>
        <span>${esc(source.trust || "")}</span>
      </div>
      <div>
        <a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.title || source.name)}</a>
        <span>${esc(source.summary || source.notes || "")}</span>
        ${
          articles.length
            ? `<div class="source-articles">${articles
                .map(
                  (article) => `
                    <a class="source-article" href="${esc(article.url)}" target="_blank" rel="noreferrer">
                      <strong>${esc(article.title)}</strong>
                      <span>${esc(article.sourceName || source.name)} · ${esc(formatShortDate(article.publishedAt))}</span>
                    </a>
                  `
                )
                .join("")}</div>`
            : ""
        }
      </div>
    `;
    sourceTape.appendChild(item);
  });
}

function render() {
  renderNote();
  renderMarketStrip();
  renderDeeperRead();
  renderAiRecommendations();
  renderAvoidList();
  renderSectorPerformance();
  renderRecommendations();
  renderOpportunities();
  renderTickerLab();
  renderCalendar();
  renderMacro();
  renderSources();
  renderScoreboard();
  renderTopDecileMonitor();
}

function setActiveView(view) {
  const knownViews = new Set(["briefing", "scoreboard", "top-decile"]);
  state.activeView = knownViews.has(view) ? view : "briefing";
  const panels = {
    briefing: $("#briefingView"),
    scoreboard: $("#scoreboardView"),
    "top-decile": $("#topDecileView")
  };
  Object.entries(panels).forEach(([key, panel]) => {
    if (!panel) return;
    panel.hidden = state.activeView !== key;
    panel.classList.toggle("active", state.activeView === key);
  });
  document.querySelectorAll("[data-view-target]").forEach((button) => {
    button.classList.toggle("active", button.dataset.viewTarget === state.activeView);
  });
  window.scrollTo({ top: 0, behavior: "smooth" });
  renderScoreboard();
  renderTopDecileMonitor();
}

function setScorebookSort(key) {
  if (state.scorebook.sortKey === key) {
    state.scorebook.sortDirection = state.scorebook.sortDirection === "asc" ? "desc" : "asc";
  } else {
    state.scorebook.sortKey = key;
    state.scorebook.sortDirection = ["modelRank", "symbol", "name", "industry"].includes(key) ? "asc" : "desc";
  }
  renderScoreboard();
}

function wireControls() {
  on("#tickerLabForm", "submit", submitTickerLab);
  on("#scoreboardSearch", "input", (event) => {
    state.scorebook.query = event.target.value || "";
    renderScoreboard();
  });
  on("#scoreboardSector", "change", (event) => {
    state.scorebook.sector = event.target.value || "";
    renderScoreboard();
  });
  document.querySelectorAll("[data-view-target]").forEach((button) => {
    button.addEventListener("click", () => setActiveView(button.dataset.viewTarget));
  });
  document.querySelectorAll("[data-score-sort]").forEach((button) => {
    button.addEventListener("click", () => setScorebookSort(button.dataset.scoreSort));
  });
}

async function loadRuntimeConfig() {
  try {
    const response = await fetch(`config/runtime.json?ts=${Date.now()}`);
    if (response.ok) {
      const payload = await response.json();
      state.tickerLab.apiBaseUrl = normalizeApiBaseUrl(payload.tickerLabApiBaseUrl || "");
    }
  } catch (error) {
    console.warn(error);
  }
  const localOverride = normalizeApiBaseUrl(localStorage.getItem("tickerLabApiBaseUrl") || "");
  if (localOverride) state.tickerLab.apiBaseUrl = localOverride;
}

async function checkTickerLabAvailability() {
  try {
    const response = await fetch(tickerLabUrl(`/api/ticker-lab/status?ts=${Date.now()}`));
    if (!response.ok) throw new Error("Ticker Lab API unavailable");
    const payload = await response.json();
    state.tickerLab.enabled = Boolean(payload.enabled);
    state.tickerLab.apiReady = Boolean(payload.enabled);
    state.tickerLab.requiresAccessCode = Boolean(payload.requiresAccessCode);
    state.tickerLab.maxTickers = payload.maxTickers || 25;
    if (payload.enabled) {
      const cacheText = payload.referenceCache?.ready
        ? ` Daily cache as of ${payload.referenceCache.asOfDate || "latest close"}.`
        : " The first score may rebuild the reference cache.";
      state.tickerLab.status = `Model API ready. Paste up to ${state.tickerLab.maxTickers} symbols.${cacheText}`;
    } else {
      state.tickerLab.status = payload.error || "Ticker Lab backend is disabled.";
    }
  } catch (error) {
    state.tickerLab.enabled = true;
    state.tickerLab.apiReady = false;
    state.tickerLab.requiresAccessCode = false;
    state.tickerLab.status = "Ticker Lab backend is not connected yet. Add the hosted API URL to config/runtime.json or run npm run dev:local.";
    console.warn(error);
  }
  renderTickerLab();
}

async function submitTickerLab(event) {
  event.preventDefault();
  const input = $("#tickerLabInput");
  const tickers = parseTickerInput(input?.value || "");
  if (!tickers.length) {
    state.tickerLab.error = "Paste at least one valid ticker symbol.";
    state.tickerLab.result = null;
    renderTickerLab();
    return;
  }
  if (!state.tickerLab.apiReady) {
    state.tickerLab.error = "Ticker Lab backend is not connected yet.";
    state.tickerLab.result = null;
    renderTickerLab();
    return;
  }

  state.tickerLab.loading = true;
  state.tickerLab.error = null;
  state.tickerLab.result = null;
  state.tickerLab.status = `Scoring ${tickers.join(", ")} against the cached S&P 500 reference universe.`;
  renderTickerLab();

  try {
    const token = $("#tickerLabToken")?.value?.trim();
    const headers = { "content-type": "application/json" };
    if (token) headers["x-ticker-lab-token"] = token;
    const response = await fetch(tickerLabUrl("/api/ticker-lab/score"), {
      method: "POST",
      headers,
      body: JSON.stringify({ tickers })
    });
    const payload = await response.json();
    if (!response.ok || payload.status === "error") throw new Error(payload.error || "Ticker scoring failed.");
    state.tickerLab.result = payload;
    state.tickerLab.status = `Scored ${payload.results?.length || 0} of ${tickers.length} requested ticker${tickers.length === 1 ? "" : "s"}.`;
  } catch (error) {
    state.tickerLab.error = error.message;
    state.tickerLab.status = "Ticker Lab scoring failed.";
  } finally {
    state.tickerLab.loading = false;
    renderTickerLab();
  }
}

async function loadSnapshot() {
  try {
    const response = await fetch(`data/snapshot.json?ts=${Date.now()}`);
    if (!response.ok) throw new Error(`Snapshot unavailable: ${response.status}`);
    state.snapshot = await response.json();
  } catch (error) {
    console.warn(error);
    state.snapshot = fallbackSnapshot;
  }
  render();
}

async function loadScorebook() {
  try {
    const response = await fetch(`data/model-scorebook.json?ts=${Date.now()}`);
    if (!response.ok) throw new Error(`Scoreboard unavailable: ${response.status}`);
    const payload = await response.json();
    state.scorebook = {
      ...state.scorebook,
      status: payload.status || "ready",
      generatedAt: payload.generatedAt || null,
      asOfDate: payload.asOfDate || null,
      rows: payload.rows || [],
      rowCount: payload.rowCount || payload.rows?.length || 0,
      model: payload.model || null,
      returnNotes: payload.returnNotes || ""
    };
  } catch (error) {
    console.warn(error);
    state.scorebook = {
      ...state.scorebook,
      status: "missing",
      rows: [],
      rowCount: 0,
      returnNotes: ""
    };
  }
  renderScoreboard();
  renderTopDecileMonitor();
}

async function loadModelMonitoring() {
  try {
    const response = await fetch(`data/model-monitoring.json?ts=${Date.now()}`);
    if (!response.ok) throw new Error(`Model monitoring unavailable: ${response.status}`);
    const payload = await response.json();
    state.monitoring = {
      ...state.monitoring,
      status: payload.status || "ready",
      generatedAt: payload.generatedAt || null,
      asOfDate: payload.asOfDate || null,
      rowCount: payload.rowCount || 0,
      topDecileCutoff: payload.topDecileCutoff || 0,
      topDecileCount: payload.topDecileCount || payload.currentTopDecile?.length || 0,
      recentEntrantCount: payload.recentEntrantCount || payload.recentEntrants?.length || 0,
      trailingReturnStatus: payload.trailingReturnStatus || "",
      marketDataStatus: payload.marketDataStatus || null,
      currentTopDecile: payload.currentTopDecile || [],
      recentEntrants: payload.recentEntrants || [],
      methodology: payload.methodology || []
    };
  } catch (error) {
    console.warn(error);
    state.monitoring = {
      ...state.monitoring,
      status: "missing",
      currentTopDecile: [],
      recentEntrants: []
    };
  }
  renderTopDecileMonitor();
}

wireControls();
loadSnapshot();
loadScorebook();
loadModelMonitoring();
loadRuntimeConfig().then(checkTickerLabAvailability);
